/**
 * PolicyRule Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policy-rules
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/policy-rules.openapi.types.js";
import { schemas } from "../schemas/policy-rules.schemas.js";

/**
 * Entity: PolicyRuleEntity
 * Description: Represents the PolicyRule domain model.
 * Source: schemas.PolicyRule
 * Type: Domain Entity (API)
 */
export const PolicyRuleEntitySchema = schemas.PolicyRule;
export type PolicyRuleEntity = components["schemas"]["PolicyRule"];
