/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pocw-attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * PocwAttestations Domain Use Cases
 * 
 * List of all use case names for the pocw-attestations domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const POCWATTESTATIONS_USE_CASES = [
  "executeAcceptPoCWAttestation",
  "executeExportPoCWAttestationPack",
  "executeGetPoCWAttestation",
  "executeListPoCWAttestations",
  "executeRejectPoCWAttestation",
  "executeSubmitPoCWAttestation"
] as const;
