/**
 * PolicyRuleRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policy-rules
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PolicyRuleRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements PolicyRuleRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  PolicyRuleRepository,
} from "@cogbazaar/services/policy-rules";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { PolicyRuleRepositoryDdb } from "./policy-rule-repository.ddb.js";

/**
 * PolicyRuleRepositoryAdapter
 *
 * Implements PolicyRuleRepository port for infrastructure layer.
 */
export class PolicyRuleRepositoryAdapter implements PolicyRuleRepository {
  private readonly ddb: PolicyRuleRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new PolicyRuleRepositoryDdb(this.dynamoClient);
  }

  async listPolicyRules(input: Parameters<PolicyRuleRepository['listPolicyRules']>[0]): Promise<Awaited<ReturnType<PolicyRuleRepository['listPolicyRules']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listPolicyRules(input);
  }

  async createPolicyRule(input: Parameters<PolicyRuleRepository['createPolicyRule']>[0]): Promise<Awaited<ReturnType<PolicyRuleRepository['createPolicyRule']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createPolicyRule(input);
  }

  async getPolicyRule(input: Parameters<PolicyRuleRepository['getPolicyRule']>[0]): Promise<Awaited<ReturnType<PolicyRuleRepository['getPolicyRule']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getPolicyRule(input);
  }
}
