/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: listings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./listing-repository.ddb.js";
export * from "./suspend-repository.ddb.js";
export * from "./listing-repository.adapter.js";
export * from "./suspend-repository.adapter.js";
