/**
 * ListingRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: listings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ListingRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ListingRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ListingRepository,
} from "@cogbazaar/services/listings";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ListingRepositoryDdb } from "./listing-repository.ddb.js";

/**
 * ListingRepositoryAdapter
 *
 * Implements ListingRepository port for infrastructure layer.
 */
export class ListingRepositoryAdapter implements ListingRepository {
  private readonly ddb: ListingRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ListingRepositoryDdb(this.dynamoClient);
  }

  async listListings(input: Parameters<ListingRepository['listListings']>[0]): Promise<Awaited<ReturnType<ListingRepository['listListings']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listListings(input);
  }

  async createListing(input: Parameters<ListingRepository['createListing']>[0]): Promise<Awaited<ReturnType<ListingRepository['createListing']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createListing(input);
  }

  async getListing(input: Parameters<ListingRepository['getListing']>[0]): Promise<Awaited<ReturnType<ListingRepository['getListing']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getListing(input);
  }

  async updateListing(input: Parameters<ListingRepository['updateListing']>[0]): Promise<Awaited<ReturnType<ListingRepository['updateListing']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateListing(input);
  }
}
