/**
 * PolicyRule Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policy-rules
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { PolicyRuleEntity } from "@cogbazaar/core/policy-rules/models/index.js";
import { policyRulesSchemas } from "@cogbazaar/core/policy-rules";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "pol";

export function createPolicyRule(overrides: Partial<PolicyRuleEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    expression: overrides.expression ?? faker.lorem.word(),
    ruleId: overrides.ruleId ?? `pol_${ulid().toLowerCase()}`,
    ruleType: overrides.ruleType ?? "dualUseBlock",
    status: overrides.status ?? "active",
    ...overrides,
  };

  return policyRulesSchemas.PolicyRule.parse(raw);
}

export function policyRuleBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createPolicyRule(overrides));
}
