/**
 * GetListing DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: listings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetListingParams } from "@cogbazaar/core/listings";

export function createGetListingRequest(overrides: Partial<GetListingParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
