/**
 * RoyaltyShare DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: royalty-shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RoyaltyShare DTOs
 *
 * DDD: Application DTOs for RoyaltyShare use cases.
 */

import type { CreateRoyaltyShareRequestInput, GetRoyaltyShareParams, ListRoyaltySharesParams } from "@cogbazaar/core/royalty-shares/types";

export type ListRoyaltySharesInput = ListRoyaltySharesParams;

export type CreateRoyaltyShareInput = CreateRoyaltyShareRequestInput;

export type GetRoyaltyShareInput = GetRoyaltyShareParams;

export type ListRoyaltySharesOutput = {};

export type CreateRoyaltyShareOutput = {};

export type GetRoyaltyShareOutput = {};
