/**
 * Handlers for RoyaltyShare
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: royalty-shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { RoyaltySharesDomainModule } from "../dependencies/royalty-shares-ddd.dependencies.js";
import type { CreateRoyaltyShareInput, GetRoyaltyShareInput, ListRoyaltySharesInput } from "@cogbazaar/services/royalty-shares";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/royalty-shares
 * Operation: listRoyaltyShares
 */
export async function listRoyaltyShares(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], jobId?: string | string[], role?: string | string[], periodKey?: string | string[], payeeParticipantId?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: RoyaltySharesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListRoyaltySharesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.royaltyShares.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/royalty-shares
 * Operation: createRoyaltyShare
 */
export async function createRoyaltyShare(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: RoyaltySharesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateRoyaltyShareInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.royaltyShares.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/royalty-shares/{shareId}
 * Operation: getRoyaltyShare
 */
export async function getRoyaltyShare(
  request: FastifyRequest<{ Params: { shareId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: RoyaltySharesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetRoyaltyShareInput = {
    shareId: request.params.shareId,
  };
  const result = await deps.useCases.royaltyShares.get.execute(input);
  return reply.code(200).send(result);
}


