/**
 * ExecuteExportPoCWAttestationPack - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pocw-attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteExportPoCWAttestationPack Use Case
 *
 * DDD: Application use case for list ExportPack.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ExportPoCWAttestationPackInput, ExportPoCWAttestationPackOutput } from "../dto/export-pack.dto";
import type { ExecutionContextService, IdGeneratorService } from "@cogbazaar/services/_shared/index.js";
import type { ExportPackRepository } from "../ports";

export class ExecuteExportPoCWAttestationPack {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly exportPack: ExportPackRepository
  ) {}

  async execute(input: ExportPoCWAttestationPackInput): Promise<ExportPoCWAttestationPackOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.pcwId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.exportPack.exportPoCWAttestationPack({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ExportPoCWAttestationPackOutput;
  }
}
