/**
 * PolicyRules DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policy-rules
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PolicyRules Domain Module - Composition root
 *
 * DDD: Composition root for policy-rules domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  PolicyRuleRepositoryAdapter,
} from "@cogbazaar/adapters/policy-rules";
import { getIdGeneratorService } from "@cogbazaar/adapters";
import type { AdapterDynamoDBClient } from "@cogbazaar/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreatePolicyRule,
  ExecuteGetPolicyRule,
  ExecuteListPolicyRules,
} from "@cogbazaar/services/policy-rules/usecases";
// Ports (interfaces)
import type {
  PolicyRuleRepository,
} from "@cogbazaar/services/policy-rules/ports";

export interface PolicyRulesDomainModule {
  repos: {
    policyRules: PolicyRuleRepository;
  };
  useCases: {
    policyRules: {
      create: ExecuteCreatePolicyRule;
      get: ExecuteGetPolicyRule;
      list: ExecuteListPolicyRules;
    };
  };
}

export function buildPolicyRulesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): PolicyRulesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      policyRules?: PolicyRuleRepository;
    } = {};

    obj.policyRules = new PolicyRuleRepositoryAdapter(dynamoClient);
    return {
      policyRules: obj.policyRules!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    policyRules: {
      create: new ExecuteCreatePolicyRule(executionContext, idGenerator, repos.policyRules),
      get: new ExecuteGetPolicyRule(executionContext, idGenerator, repos.policyRules),
      list: new ExecuteListPolicyRules(executionContext, idGenerator, repos.policyRules),
    },
  };
  return { repos, useCases: useCases as PolicyRulesDomainModule["useCases"] };
}
