/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: royalty-shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * RoyaltyShares Domain Use Cases
 * 
 * List of all use case names for the royalty-shares domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const ROYALTYSHARES_USE_CASES = [
  "executeCreateRoyaltyShare",
  "executeGetRoyaltyShare",
  "executeListRoyaltyShares"
] as const;
