/**
 * CreateGrantPool handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grant-pools
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createGrantPool } from "@cogbazaar/api-server/domains/grant-pools/handlers";
import type { GrantPoolsDDDDependencies } from "@cogbazaar/api-server/domains/grant-pools";
import { createGrantPool as createGrantPoolEntity } from "@cogbazaar/factories/grant-pools";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@cogbazaar/tests/shared";
import { GRANTPOOLS_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateGrantPool", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: GrantPoolsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<GrantPoolsDDDDependencies>(
      GRANTPOOLS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createGrantPoolEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateGrantPool, "execute").mockResolvedValue(useCaseResult);

    await createGrantPool(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateGrantPool.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
