/**
 * GetGrantPool handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grant-pools
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getGrantPool } from "@cogbazaar/api-server/domains/grant-pools/handlers";
import type { GrantPoolsDDDDependencies } from "@cogbazaar/api-server/domains/grant-pools";
import { createGrantPool as createGrantPoolEntity } from "@cogbazaar/factories/grant-pools";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@cogbazaar/tests/shared";
import { GRANTPOOLS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetGrantPool", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: GrantPoolsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<GrantPoolsDDDDependencies>(
      GRANTPOOLS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createGrantPoolEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetGrantPool, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { poolId: entity.id };

    await getGrantPool(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetGrantPool.execute).toHaveBeenCalledWith(expect.objectContaining({ poolId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { poolId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetGrantPool, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getGrantPool(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
