/**
 * JobRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * JobRepository Port
 *
 * DDD: Application port for jobrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateJobInput, CreateJobOutput, GetJobInput, GetJobOutput, ListJobsInput, ListJobsOutput, UpdateJobInput, UpdateJobOutput } from "../dto/job.dto";
export interface JobRepository {
  listJobs(input: ListJobsInput): Promise<ListJobsOutput>;
  createJob(input: CreateJobInput): Promise<CreateJobOutput>;
  getJob(input: GetJobInput): Promise<GetJobOutput>;
  updateJob(input: UpdateJobInput): Promise<UpdateJobOutput>;
}

export type { CreateJobInput, CreateJobOutput, GetJobInput, GetJobOutput, ListJobsInput, ListJobsOutput, UpdateJobInput, UpdateJobOutput } from "../dto/job.dto";
