/**
 * RefundRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RefundRepository Port
 *
 * DDD: Application port for refundrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { RefundJobInput, RefundJobOutput } from "../dto/refund.dto";
export interface RefundRepository {
  refundJob(input: RefundJobInput): Promise<RefundJobOutput>;
}

export type { RefundJobInput, RefundJobOutput } from "../dto/refund.dto";
