/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grant-pools
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * GrantPools Domain Use Cases
 * 
 * List of all use case names for the grant-pools domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const GRANTPOOLS_USE_CASES = [
  "executeApproveGrantPoolDisbursement",
  "executeCreateGrantPool",
  "executeDeclareGrantPoolMetric",
  "executeGetGrantPool",
  "executeListGrantPools"
] as const;
