/**
 * ExecuteGetListing - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: listings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetListing Use Case
 *
 * DDD: Application use case for get Listing.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetListingInput, GetListingOutput } from "../dto/listing.dto";
import type { ExecutionContextService, IdGeneratorService } from "@cogbazaar/services/_shared/index.js";
import type { ListingRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetListing {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly listing: ListingRepository
  ) {}

  async execute(input: GetListingInput): Promise<GetListingOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.lstId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).listingId) {
      throw new ValidationError("listingId is required");
    }
    const listingId = (input as any).listingId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.listing.getListing({ listingId: listingId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${listingId}`);
    }

    return entity as GetListingOutput;
  }
}
