/**
 * ExecuteUpdateListing - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: listings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpdateListing Use Case
 *
 * DDD: Application use case for update Listing.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpdateListingInput, UpdateListingOutput } from "../dto/listing.dto";
import type { ExecutionContextService, IdGeneratorService } from "@cogbazaar/services/_shared/index.js";
import type { ListingRepository } from "../ports";
import { NotFoundError, PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteUpdateListing {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly listing: ListingRepository
  ) {}

  async execute(input: UpdateListingInput): Promise<UpdateListingOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.lstId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).listingId) {
      throw new ValidationError("listingId is required");
    }
    const listingId = (input as any).listingId;

    // Load existing entity
    const existing = await this.listing.getListing({ listingId: listingId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!existing) {
      throw new NotFoundError(`Entity not found: ${listingId}`);
    }
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.listing.updateListing({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as UpdateListingOutput;
  }
}
