/**
 * ExecuteCreateListing - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: listings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateListing Use Case
 *
 * DDD: Application use case for create Listing.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateListingInput, CreateListingOutput } from "../dto/listing.dto";
import type { ExecutionContextService, IdGeneratorService } from "@cogbazaar/services/_shared/index.js";
import type { ListingRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateListing {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly listing: ListingRepository
  ) {}

  async execute(input: CreateListingInput): Promise<CreateListingOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.lstId();

    // All field names extracted from OpenAPI spec: computeToDataEligible, currency, dualUseFlag, licenceClass, listingType, priceAmount, sellerParticipantId, status, supportedPocwFormats, takeRateBps, title
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.sellerParticipantId) {
      throw new ValidationError("sellerParticipantId is required");
    }
    if (!input.priceAmount) {
      throw new ValidationError("priceAmount is required");
    }
    if (!input.currency) {
      throw new ValidationError("currency is required");
    }
    if (!input.listingType) {
      throw new ValidationError("listingType is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (listings domain)
    const entityId = this.idGenerator.lstId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.listing.createListing({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateListingOutput;
  }
}
