/**
 * ExecuteDeclareGrantPoolMetric - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grant-pools
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteDeclareGrantPoolMetric Use Case
 *
 * DDD: Application use case for get DeclareMetric.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { DeclareGrantPoolMetricInput, DeclareGrantPoolMetricOutput } from "../dto/declare-metric.dto";
import type { ExecutionContextService, IdGeneratorService } from "@cogbazaar/services/_shared/index.js";
import type { DeclareMetricRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteDeclareGrantPoolMetric {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly declareMetric: DeclareMetricRepository
  ) {}

  async execute(input: DeclareGrantPoolMetricInput): Promise<DeclareGrantPoolMetricOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.grpId();

    // All field names extracted from OpenAPI spec: claimantParticipantId, evidence, metricValue
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).poolId) {
      throw new ValidationError("poolId is required");
    }
    const poolId = (input as any).poolId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.declareMetric.declareGrantPoolMetric({ poolId: poolId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${poolId}`);
    }

    return entity as DeclareGrantPoolMetricOutput;
  }
}
