/**
 * ExecuteApproveGrantPoolDisbursement - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grant-pools
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteApproveGrantPoolDisbursement Use Case
 *
 * DDD: Application use case for create ApproveDisbursement.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ApproveGrantPoolDisbursementInput, ApproveGrantPoolDisbursementOutput } from "../dto/approve-disbursement.dto";
import type { ExecutionContextService, IdGeneratorService } from "@cogbazaar/services/_shared/index.js";
import type { ApproveDisbursementRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteApproveGrantPoolDisbursement {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly approveDisbursement: ApproveDisbursementRepository
  ) {}

  async execute(input: ApproveGrantPoolDisbursementInput): Promise<ApproveGrantPoolDisbursementOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.grpId();

    // All field names extracted from OpenAPI spec: declarationId, note
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.declarationId) {
      throw new ValidationError("declarationId is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (grant-pools domain)
    const entityId = this.idGenerator.grpId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.approveDisbursement.approveGrantPoolDisbursement({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as ApproveGrantPoolDisbursementOutput;
  }
}
