/**
 * ExecuteListGrantPools - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grant-pools
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListGrantPools Use Case
 *
 * DDD: Application use case for list GrantPool.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListGrantPoolsInput, ListGrantPoolsOutput } from "../dto/grant-pool.dto";
import type { ExecutionContextService, IdGeneratorService } from "@cogbazaar/services/_shared/index.js";
import type { GrantPoolRepository } from "../ports";

export class ExecuteListGrantPools {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly grantPool: GrantPoolRepository
  ) {}

  async execute(input: ListGrantPoolsInput): Promise<ListGrantPoolsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.grpId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.grantPool.listGrantPools({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListGrantPoolsOutput;
  }
}
