/**
 * Repository interface for PocwAttestation
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: pocw-attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  PocwAttestationEntity
} from "../models/pocw-attestation.entity.js";
import type {
  ListPoCWAttestationsParams,
  PoCWAttestation
} from "../types/index.js";
/**
 * PocwAttestationRepository Interface
 */
export interface PocwAttestationRepository extends CreateReadRepository<PocwAttestationEntity, PoCWAttestation, string, ListPoCWAttestationsParams> {

}
