/**
 * GetPoCWAttestation handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pocw-attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getPoCWAttestation } from "@cogbazaar/api-server/domains/pocw-attestations/handlers";
import type { PocwAttestationsDDDDependencies } from "@cogbazaar/api-server/domains/pocw-attestations";
import { createPocwAttestation as createPocwAttestationEntity } from "@cogbazaar/factories/pocw-attestations";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@cogbazaar/tests/shared";
import { POCWATTESTATIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetPoCWAttestation", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: PocwAttestationsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<PocwAttestationsDDDDependencies>(
      POCWATTESTATIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createPocwAttestationEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetPoCWAttestation, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { attestationId: entity.id };

    await getPoCWAttestation(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetPoCWAttestation.execute).toHaveBeenCalledWith(expect.objectContaining({ attestationId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { attestationId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetPoCWAttestation, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getPoCWAttestation(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
