/**
 * SubmitPoCWAttestation handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pocw-attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { submitPoCWAttestation } from "@cogbazaar/api-server/domains/pocw-attestations/handlers";
import type { PocwAttestationsDDDDependencies } from "@cogbazaar/api-server/domains/pocw-attestations";
import { createPocwAttestation as createPocwAttestationEntity } from "@cogbazaar/factories/pocw-attestations";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@cogbazaar/tests/shared";
import { POCWATTESTATIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("SubmitPoCWAttestation", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: PocwAttestationsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<PocwAttestationsDDDDependencies>(
      POCWATTESTATIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createPocwAttestationEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeSubmitPoCWAttestation, "execute").mockResolvedValue(useCaseResult);

    await submitPoCWAttestation(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeSubmitPoCWAttestation.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
