/**
 * Routes for Listing
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: listings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createListing, getListing, listListings, updateListing } from "../handlers/listing.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function listingRoutes(fastify: FastifyInstance) {
  // POST /v1/listings (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/listings",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getListingsDependenciesForRequest();
        await createListing(request, reply, deps);
      });
    }
  );


  // GET /v1/listings (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/listings",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getListingsDependenciesForRequest();
        await listListings(request, reply, deps);
      });
    }
  );


  // GET /v1/listings/{listingId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/listings/:listingId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { listingId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getListingsDependenciesForRequest();
        await getListing(request, reply, deps);
      });
    }
  );


  // PATCH /v1/listings/{listingId} (unscoped; scope set for security middleware)
  fastify.patch(
    "/v1/listings/:listingId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { listingId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getListingsDependenciesForRequest();
        await updateListing(request, reply, deps);
      });
    }
  );


}
