/**
 * Routes for Suspend
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: listings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { suspendListing } from "../handlers/suspend.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function suspendRoutes(fastify: FastifyInstance) {
  // POST /v1/listings/{listingId}/suspend (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/listings/:listingId/suspend",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { listingId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getListingsDependenciesForRequest();
        await suspendListing(request, reply, deps);
      });
    }
  );


}
