/**
 * ApproveDisbursementRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grant-pools
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ApproveDisbursementRepository Port
 *
 * DDD: Application port for approvedisbursementrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ApproveGrantPoolDisbursementInput, ApproveGrantPoolDisbursementOutput } from "../dto/approve-disbursement.dto";
export interface ApproveDisbursementRepository {
  approveGrantPoolDisbursement(input: ApproveGrantPoolDisbursementInput): Promise<ApproveGrantPoolDisbursementOutput>;
}

export type { ApproveGrantPoolDisbursementInput, ApproveGrantPoolDisbursementOutput } from "../dto/approve-disbursement.dto";
