/**
 * DeclareMetricRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grant-pools
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DeclareMetricRepository Port
 *
 * DDD: Application port for declaremetricrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { DeclareGrantPoolMetricInput, DeclareGrantPoolMetricOutput } from "../dto/declare-metric.dto";
export interface DeclareMetricRepository {
  declareGrantPoolMetric(input: DeclareGrantPoolMetricInput): Promise<DeclareGrantPoolMetricOutput>;
}

export type { DeclareGrantPoolMetricInput, DeclareGrantPoolMetricOutput } from "../dto/declare-metric.dto";
