/**
 * GrantPoolRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grant-pools
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * GrantPoolRepository Port
 *
 * DDD: Application port for grantpoolrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateGrantPoolInput, CreateGrantPoolOutput, GetGrantPoolInput, GetGrantPoolOutput, ListGrantPoolsInput, ListGrantPoolsOutput } from "../dto/grant-pool.dto";
export interface GrantPoolRepository {
  listGrantPools(input: ListGrantPoolsInput): Promise<ListGrantPoolsOutput>;
  createGrantPool(input: CreateGrantPoolInput): Promise<CreateGrantPoolOutput>;
  getGrantPool(input: GetGrantPoolInput): Promise<GetGrantPoolOutput>;
}

export type { CreateGrantPoolInput, CreateGrantPoolOutput, GetGrantPoolInput, GetGrantPoolOutput, ListGrantPoolsInput, ListGrantPoolsOutput } from "../dto/grant-pool.dto";
