/**
 * PocwAttestation Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pocw-attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { PocwAttestationEntity } from "@cogbazaar/core/pocw-attestations/models/index.js";
import { pocwAttestationsSchemas } from "@cogbazaar/core/pocw-attestations";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "pcw";

export function createPocwAttestation(overrides: Partial<PocwAttestationEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    attestationId: overrides.attestationId ?? `pcw_${ulid().toLowerCase()}`,
    jobId: overrides.jobId ?? faker.string.uuid(),
    providerParticipantId: overrides.providerParticipantId ?? faker.string.uuid(),
    status: overrides.status ?? "pending",
    submittedAt: overrides.submittedAt ?? new Date().toISOString(),
    ...overrides,
  };

  return pocwAttestationsSchemas.PoCWAttestation.parse(raw);
}

export function pocwAttestationBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createPocwAttestation(overrides));
}
