/**
 * ExportPack DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pocw-attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExportPack DTOs
 *
 * DDD: Application DTOs for ExportPack use cases.
 */

import type { ExportPoCWAttestationPackParams } from "@cogbazaar/core/pocw-attestations/types";

export type ExportPoCWAttestationPackInput = ExportPoCWAttestationPackParams;

export type ExportPoCWAttestationPackOutput = {};
