/**
 * PocwAttestation DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pocw-attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PocwAttestation DTOs
 *
 * DDD: Application DTOs for PocwAttestation use cases.
 */

import type { GetPoCWAttestationParams, ListPoCWAttestationsParams, SubmitPoCWAttestationRequestInput } from "@cogbazaar/core/pocw-attestations/types";

export type ListPoCWAttestationsInput = ListPoCWAttestationsParams;

export type SubmitPoCWAttestationInput = SubmitPoCWAttestationRequestInput;

export type GetPoCWAttestationInput = GetPoCWAttestationParams;

export type ListPoCWAttestationsOutput = {};

export type SubmitPoCWAttestationOutput = {};

export type GetPoCWAttestationOutput = {};
