/**
 * GetListing handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: listings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getListing } from "@cogbazaar/api-server/domains/listings/handlers";
import type { ListingsDDDDependencies } from "@cogbazaar/api-server/domains/listings";
import { createListing as createListingEntity } from "@cogbazaar/factories/listings";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@cogbazaar/tests/shared";
import { LISTINGS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetListing", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ListingsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ListingsDDDDependencies>(
      LISTINGS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createListingEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetListing, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { listingId: entity.id };

    await getListing(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetListing.execute).toHaveBeenCalledWith(expect.objectContaining({ listingId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { listingId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetListing, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getListing(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
