/**
 * Routes for AcceptRoute
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { acceptJobRoute } from "../handlers/accept-route.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function acceptRouteRoutes(fastify: FastifyInstance) {
  // POST /v1/jobs/{jobId}/accept-route (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/jobs/:jobId/accept-route",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { jobId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getJobsDependenciesForRequest();
        await acceptJobRoute(request, reply, deps);
      });
    }
  );


}
