/**
 * Domain routes – register all domain route modules.
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Rescans platform/api-server/src/domains and includes only domains that have
 * routes/index.ts and dependencies/{domain}-ddd.dependencies.ts.
 * Extension excludes/imports from x-codegen.api-server.extensions in OpenAPI YAML.
 */

import type { FastifyInstance } from "fastify";
import { registerDomainFromModule } from "./route-registration.js";

// Static imports so the bundle includes all domain route modules
import * as grantPoolsRoutes from "../../domains/grant-pools/routes/index.js";
import * as identityRoutes from "../../domains/identity/routes/index.js";
import * as jobsRoutes from "../../domains/jobs/routes/index.js";
import * as listingsRoutes from "../../domains/listings/routes/index.js";
import * as pocwAttestationsRoutes from "../../domains/pocw-attestations/routes/index.js";
import * as policyRulesRoutes from "../../domains/policy-rules/routes/index.js";
import * as royaltySharesRoutes from "../../domains/royalty-shares/routes/index.js";

const DOMAIN_MODULES: Array<{
  domain: string;
  mod: Record<string, unknown>;
  exclude?: string[];
}> = [
  { domain: "grant-pools", mod: grantPoolsRoutes },
  {
    domain: "identity", mod: identityRoutes,
    exclude: ["authRoutes", "loginRoutes", "logoutRoutes", "signupRoutes", "sessionRoutes", "refreshRoutes", "tokenRoutes", "profileRoutes"],
  },
  { domain: "jobs", mod: jobsRoutes },
  { domain: "listings", mod: listingsRoutes },
  { domain: "pocw-attestations", mod: pocwAttestationsRoutes },
  { domain: "policy-rules", mod: policyRulesRoutes },
  { domain: "royalty-shares", mod: royaltySharesRoutes },
];

export async function registerAllDomainRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  console.log("[DEBUG] Registering domain routes...");
  try {
    for (const { domain, mod, exclude } of DOMAIN_MODULES) {
      await registerDomainFromModule(fastify, domain, mod, exclude ?? []);
    }
    console.log("[DEBUG] ✅ All domain routes registered");
  } catch (error: unknown) {
    const err = error instanceof Error ? error : new Error(String(error));
    console.error("[DEBUG] ❌ Error registering domain routes:", err.message);
    if (err.stack) console.error(err.stack);
    throw error;
  }
}
