/**
 * System Routes - Health check and routes listing
 *
 * AUTO-GENERATED by codegen (api_server_system_routes). Do not edit by hand.
 * Domains and routeExamples are derived from discovered api-server domains and
 * each domain's OpenAPI bundled spec.
 */

import type { FastifyInstance } from "fastify";
import {
  getCoreTableName,
  getBaseTableName,
  getAnalyticsTableName,
} from "@cogbazaar/adapters";
import { getRegisteredRoutes } from "./route-registry.js";

/**
 * Register system routes (health check, routes listing)
 */
export function registerSystemRoutes(fastify: FastifyInstance): void {
  // Health check (public - no auth required)
  fastify.get("/health", { config: { scope: "public" } }, async () => {
    try {
      const coreTable = getCoreTableName();
      const baseTable = getBaseTableName();
      const analyticsTable = getAnalyticsTableName();
      return {
        status: "ok",
        database: "dynamodb",
        tables: {
          core: coreTable,
          base: baseTable,
          analytics: analyticsTable,
        },
      };
    } catch (error: unknown) {
      const errorMessage =
        error instanceof Error ? error.message : String(error);
      fastify.log.warn({ error: errorMessage }, "Health check failed");
      return { status: "error", database: "disconnected", error: errorMessage };
    }
  });

  // Routes listing endpoint (public)
  fastify.get("/routes", { config: { scope: "public" } }, async () => {
    const domains = [
      "grant-pools", "identity", "jobs", "listings", "pocw-attestations", "policy-rules", "royalty-shares"
    ];

    const routeExamples: Record<
      string,
      Array<{ method: string; path: string; description?: string }>
    > = {
      "grant-pools": [{ method: "GET", path: "/v1/grant-pools" }, { method: "POST", path: "/v1/grant-pools" }, { method: "GET", path: "/v1/grant-pools/:poolId" }, { method: "POST", path: "/v1/grant-pools/:poolId/declare-metric" }, { method: "POST", path: "/v1/grant-pools/:poolId/approve-disbursement" }],
      identity: [],
      jobs: [{ method: "GET", path: "/v1/jobs" }, { method: "POST", path: "/v1/jobs" }, { method: "GET", path: "/v1/jobs/:jobId" }, { method: "PATCH", path: "/v1/jobs/:jobId" }, { method: "POST", path: "/v1/jobs/:jobId/match" }, { method: "POST", path: "/v1/jobs/:jobId/accept-route" }, { method: "POST", path: "/v1/jobs/:jobId/cancel" }, { method: "POST", path: "/v1/jobs/:jobId/dispute" }, { method: "POST", path: "/v1/jobs/:jobId/refund" }],
      listings: [{ method: "GET", path: "/v1/listings" }, { method: "POST", path: "/v1/listings" }, { method: "GET", path: "/v1/listings/:listingId" }, { method: "PATCH", path: "/v1/listings/:listingId" }, { method: "POST", path: "/v1/listings/:listingId/suspend" }],
      "pocw-attestations": [{ method: "GET", path: "/v1/pocw-attestations" }, { method: "POST", path: "/v1/pocw-attestations" }, { method: "GET", path: "/v1/pocw-attestations/:attestationId" }, { method: "POST", path: "/v1/pocw-attestations/:attestationId/accept" }, { method: "POST", path: "/v1/pocw-attestations/:attestationId/reject" }, { method: "POST", path: "/v1/pocw-attestations/:attestationId/export-pack" }],
      "policy-rules": [{ method: "GET", path: "/v1/policy-rules" }, { method: "POST", path: "/v1/policy-rules" }, { method: "GET", path: "/v1/policy-rules/:ruleId" }],
      "royalty-shares": [{ method: "GET", path: "/v1/royalty-shares" }, { method: "POST", path: "/v1/royalty-shares" }, { method: "GET", path: "/v1/royalty-shares/:shareId" }],
    };

    return {
      baseUrl: "http://localhost:4000",
      routePattern: "/orgs/:orgId/{domain}/{resource}",
      authentication:
        "All routes (except /health and /routes) require JWT token in Authorization header",
      domains: domains.sort(),
      routeExamples,
      systemRoutes: [
        { method: "GET", path: "/health", description: "Health check endpoint" },
        { method: "GET", path: "/routes", description: "List available routes" },
      ],
      note: "Replace :orgId with actual organization ID. All domain routes require authentication.",
    };
  });

  // Full route list for API tester page (public)
  fastify.get("/routes/full", { config: { scope: "public" } }, async () => {
    const routes = getRegisteredRoutes();
    const byDomain: Record<
      string,
      Array<{ method: string; path: string }>
    > = {};
    const system: Array<{ method: string; path: string }> = [];
    for (const r of routes) {
      const m = r.path.match(/^\/orgs\/:orgId\/([^/]+)/);
      if (m) {
        const domain = m[1];
        if (!byDomain[domain]) byDomain[domain] = [];
        byDomain[domain].push(r);
      } else {
        system.push(r);
      }
    }
    return {
      baseUrl: "http://localhost:4000",
      total: routes.length,
      system,
      byDomain: Object.keys(byDomain)
        .sort()
        .reduce(
          (acc, k) => ({ ...acc, [k]: byDomain[k] }),
          {} as Record<string, Array<{ method: string; path: string }>>,
        ),
    };
  });
}
