/**
 * RoyaltyShare Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: royalty-shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/royalty-shares.openapi.types.js";
import { schemas } from "../schemas/royalty-shares.schemas.js";

/**
 * Entity: RoyaltyShareEntity
 * Description: Represents the RoyaltyShare domain model.
 * Source: schemas.RoyaltyShare
 * Type: Domain Entity (API)
 */
export const RoyaltyShareEntitySchema = schemas.RoyaltyShare;
export type RoyaltyShareEntity = components["schemas"]["RoyaltyShare"];
