/**
 * GrantPool Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grant-pools
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { GrantPoolEntity } from "@cogbazaar/core/grant-pools/models/index.js";
import { grantPoolsSchemas } from "@cogbazaar/core/grant-pools";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "grp";

export function createGrantPool(overrides: Partial<GrantPoolEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    budgetAmount: overrides.budgetAmount ?? faker.number.int(),
    currency: overrides.currency ?? faker.lorem.word(),
    metric: overrides.metric ?? faker.lorem.word(),
    name: overrides.name ?? faker.person.fullName(),
    poolId: overrides.poolId ?? `grp_${ulid().toLowerCase()}`,
    status: overrides.status ?? "open",
    ...overrides,
  };

  return grantPoolsSchemas.GrantPool.parse(raw);
}

export function grantPoolBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createGrantPool(overrides));
}
