/**
 * Jobs DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Jobs Domain Module - Composition root
 *
 * DDD: Composition root for jobs domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AcceptRouteRepositoryAdapter,
  CancelRepositoryAdapter,
  DisputeRepositoryAdapter,
  JobRepositoryAdapter,
  MatchRepositoryAdapter,
  RefundRepositoryAdapter,
} from "@cogbazaar/adapters/jobs";
import { getIdGeneratorService } from "@cogbazaar/adapters";
import type { AdapterDynamoDBClient } from "@cogbazaar/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteAcceptJobRoute,
  ExecuteCancelJob,
  ExecuteCreateJob,
  ExecuteDisputeJob,
  ExecuteGetJob,
  ExecuteListJobs,
  ExecuteMatchJob,
  ExecuteRefundJob,
  ExecuteUpdateJob,
} from "@cogbazaar/services/jobs/usecases";
// Ports (interfaces)
import type {
  AcceptRouteRepository,
  CancelRepository,
  DisputeRepository,
  JobRepository,
  MatchRepository,
  RefundRepository,
} from "@cogbazaar/services/jobs/ports";

export interface JobsDomainModule {
  repos: {
    acceptRoutes: AcceptRouteRepository;
    cancels: CancelRepository;
    disputes: DisputeRepository;
    jobs: JobRepository;
    matches: MatchRepository;
    refunds: RefundRepository;
  };
  useCases: {
    acceptRoutes: {
      get: ExecuteAcceptJobRoute;
    };
    cancels: {
      update: ExecuteCancelJob;
    };
    disputes: {
      get: ExecuteDisputeJob;
    };
    jobs: {
      create: ExecuteCreateJob;
      get: ExecuteGetJob;
      list: ExecuteListJobs;
      update: ExecuteUpdateJob;
    };
    matches: {
      get: ExecuteMatchJob;
    };
    refunds: {
      get: ExecuteRefundJob;
    };
  };
}

export function buildJobsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): JobsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      acceptRoutes?: AcceptRouteRepository;
      cancels?: CancelRepository;
      disputes?: DisputeRepository;
      jobs?: JobRepository;
      matches?: MatchRepository;
      refunds?: RefundRepository;
    } = {};

    obj.acceptRoutes = new AcceptRouteRepositoryAdapter(dynamoClient);
    obj.cancels = new CancelRepositoryAdapter(dynamoClient);
    obj.disputes = new DisputeRepositoryAdapter(dynamoClient);
    obj.jobs = new JobRepositoryAdapter(dynamoClient);
    obj.matches = new MatchRepositoryAdapter(dynamoClient);
    obj.refunds = new RefundRepositoryAdapter(dynamoClient);
    return {
      acceptRoutes: obj.acceptRoutes!,
      cancels: obj.cancels!,
      disputes: obj.disputes!,
      jobs: obj.jobs!,
      matches: obj.matches!,
      refunds: obj.refunds!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    acceptRoutes: {
      get: new ExecuteAcceptJobRoute(executionContext, idGenerator, repos.acceptRoutes),
    },
    cancels: {
      update: new ExecuteCancelJob(executionContext, idGenerator, repos.cancels),
    },
    disputes: {
      get: new ExecuteDisputeJob(executionContext, idGenerator, repos.disputes),
    },
    jobs: {
      create: new ExecuteCreateJob(executionContext, idGenerator, repos.jobs),
      get: new ExecuteGetJob(executionContext, idGenerator, repos.jobs),
      list: new ExecuteListJobs(executionContext, idGenerator, repos.jobs),
      update: new ExecuteUpdateJob(executionContext, idGenerator, repos.jobs),
    },
    matches: {
      get: new ExecuteMatchJob(executionContext, idGenerator, repos.matches),
    },
    refunds: {
      get: new ExecuteRefundJob(executionContext, idGenerator, repos.refunds),
    },
  };
  return { repos, useCases: useCases as JobsDomainModule["useCases"] };
}
