/**
 * GetPolicyRule DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policy-rules
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetPolicyRuleParams } from "@cogbazaar/core/policy-rules";

export function createGetPolicyRuleRequest(overrides: Partial<GetPolicyRuleParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
