/**
 * CancelRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CancelRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements CancelRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  CancelRepository,
} from "@cogbazaar/services/jobs";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { CancelRepositoryDdb } from "./cancel-repository.ddb.js";

/**
 * CancelRepositoryAdapter
 *
 * Implements CancelRepository port for infrastructure layer.
 */
export class CancelRepositoryAdapter implements CancelRepository {
  private readonly ddb: CancelRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new CancelRepositoryDdb(this.dynamoClient);
  }

  async getJob(input: Parameters<CancelRepository['getJob']>[0]): Promise<Awaited<ReturnType<CancelRepository['getJob']>>> {
    return await this.ddb.getJob(input);
  }

  async cancelJob(input: Parameters<CancelRepository['cancelJob']>[0]): Promise<Awaited<ReturnType<CancelRepository['cancelJob']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.cancelJob(input);
  }
}
