/**
 * JobRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * JobRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements JobRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  JobRepository,
} from "@cogbazaar/services/jobs";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { JobRepositoryDdb } from "./job-repository.ddb.js";

/**
 * JobRepositoryAdapter
 *
 * Implements JobRepository port for infrastructure layer.
 */
export class JobRepositoryAdapter implements JobRepository {
  private readonly ddb: JobRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new JobRepositoryDdb(this.dynamoClient);
  }

  async listJobs(input: Parameters<JobRepository['listJobs']>[0]): Promise<Awaited<ReturnType<JobRepository['listJobs']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listJobs(input);
  }

  async createJob(input: Parameters<JobRepository['createJob']>[0]): Promise<Awaited<ReturnType<JobRepository['createJob']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createJob(input);
  }

  async getJob(input: Parameters<JobRepository['getJob']>[0]): Promise<Awaited<ReturnType<JobRepository['getJob']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getJob(input);
  }

  async updateJob(input: Parameters<JobRepository['updateJob']>[0]): Promise<Awaited<ReturnType<JobRepository['updateJob']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateJob(input);
  }
}
