/**
 * MatchRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * MatchRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements MatchRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  MatchRepository,
} from "@cogbazaar/services/jobs";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { MatchRepositoryDdb } from "./match-repository.ddb.js";

/**
 * MatchRepositoryAdapter
 *
 * Implements MatchRepository port for infrastructure layer.
 */
export class MatchRepositoryAdapter implements MatchRepository {
  private readonly ddb: MatchRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new MatchRepositoryDdb(this.dynamoClient);
  }

  async matchJob(input: Parameters<MatchRepository['matchJob']>[0]): Promise<Awaited<ReturnType<MatchRepository['matchJob']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.matchJob(input);
  }
}
