/**
 * RefundRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RefundRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements RefundRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  RefundRepository,
} from "@cogbazaar/services/jobs";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { RefundRepositoryDdb } from "./refund-repository.ddb.js";

/**
 * RefundRepositoryAdapter
 *
 * Implements RefundRepository port for infrastructure layer.
 */
export class RefundRepositoryAdapter implements RefundRepository {
  private readonly ddb: RefundRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new RefundRepositoryDdb(this.dynamoClient);
  }

  async refundJob(input: Parameters<RefundRepository['refundJob']>[0]): Promise<Awaited<ReturnType<RefundRepository['refundJob']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.refundJob(input);
  }
}
