/**
 * ListGrantPool DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grant-pools
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListGrantPoolsParams } from "@cogbazaar/core/grant-pools";

export function createListGrantPoolRequest(overrides: Partial<ListGrantPoolsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
