/**
 * AcceptRoute DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AcceptRoute DTOs
 *
 * DDD: Application DTOs for AcceptRoute use cases.
 */

import type { AcceptJobRouteParams, AcceptJobRouteRequestInput } from "@cogbazaar/core/jobs/types";

export type AcceptJobRouteInput = AcceptJobRouteParams & AcceptJobRouteRequestInput;

export type AcceptJobRouteOutput = {};
