/**
 * Dispute DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Dispute DTOs
 *
 * DDD: Application DTOs for Dispute use cases.
 */

import type { DisputeJobParams, DisputeJobRequestInput } from "@cogbazaar/core/jobs/types";

export type DisputeJobInput = DisputeJobParams & DisputeJobRequestInput;

export type DisputeJobOutput = {};
