/**
 * Routes for GrantPool
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grant-pools
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createGrantPool, getGrantPool, listGrantPools } from "../handlers/grant-pool.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function grantPoolRoutes(fastify: FastifyInstance) {
  // POST /v1/grant-pools (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/grant-pools",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getGrantPoolsDependenciesForRequest();
        await createGrantPool(request, reply, deps);
      });
    }
  );


  // GET /v1/grant-pools (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/grant-pools",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getGrantPoolsDependenciesForRequest();
        await listGrantPools(request, reply, deps);
      });
    }
  );


  // GET /v1/grant-pools/{poolId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/grant-pools/:poolId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { poolId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getGrantPoolsDependenciesForRequest();
        await getGrantPool(request, reply, deps);
      });
    }
  );


}
