/**
 * ExecuteGetPolicyRule - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policy-rules
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetPolicyRule Use Case
 *
 * DDD: Application use case for get PolicyRule.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetPolicyRuleInput, GetPolicyRuleOutput } from "../dto/policy-rule.dto";
import type { ExecutionContextService, IdGeneratorService } from "@cogbazaar/services/_shared/index.js";
import type { PolicyRuleRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetPolicyRule {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly policyRule: PolicyRuleRepository
  ) {}

  async execute(input: GetPolicyRuleInput): Promise<GetPolicyRuleOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.polId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).ruleId) {
      throw new ValidationError("ruleId is required");
    }
    const ruleId = (input as any).ruleId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.policyRule.getPolicyRule({ ruleId: ruleId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${ruleId}`);
    }

    return entity as GetPolicyRuleOutput;
  }
}
