/**
 * ExecuteListPolicyRules - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policy-rules
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListPolicyRules Use Case
 *
 * DDD: Application use case for list PolicyRule.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListPolicyRulesInput, ListPolicyRulesOutput } from "../dto/policy-rule.dto";
import type { ExecutionContextService, IdGeneratorService } from "@cogbazaar/services/_shared/index.js";
import type { PolicyRuleRepository } from "../ports";

export class ExecuteListPolicyRules {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly policyRule: PolicyRuleRepository
  ) {}

  async execute(input: ListPolicyRulesInput): Promise<ListPolicyRulesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.polId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.policyRule.listPolicyRules({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListPolicyRulesOutput;
  }
}
