/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: policy-rules
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @cogbazaar/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@cogbazaar/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@cogbazaar/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@cogbazaar/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@cogbazaar/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@cogbazaar/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _grantPools from "./grant-pools/index.js";
import * as _identity from "./identity/index.js";
import * as _jobs from "./jobs/index.js";
import * as _listings from "./listings/index.js";
import * as _pocwAttestations from "./pocw-attestations/index.js";
import * as _policyRules from "./policy-rules/index.js";
import * as _royaltyShares from "./royalty-shares/index.js";

// Export as namespaces
export const _shared = __shared;
export const grantPools = _grantPools;
export const identity = _identity;
export const jobs = _jobs;
export const listings = _listings;
export const pocwAttestations = _pocwAttestations;
export const policyRules = _policyRules;
export const royaltyShares = _royaltyShares;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@cogbazaar/core"; activity.types.*
//   - Direct exports: import * from "@cogbazaar/core/activity/types/index.js"
//   - Direct exports: import * from "@cogbazaar/core/activity/repositories/index.js"
//   - Direct exports: import * from "@cogbazaar/core/activity/models/index.js"
//   - Direct exports: import * from "@cogbazaar/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// GrantPools Service
export { schemas as GrantPoolsSchemas } from "./grant-pools/schemas/grant-pools.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// Jobs Service
export { schemas as JobsSchemas } from "./jobs/schemas/jobs.schemas.js";

// Listings Service
export { schemas as ListingsSchemas } from "./listings/schemas/listings.schemas.js";

// PocwAttestations Service
export { schemas as PocwAttestationsSchemas } from "./pocw-attestations/schemas/pocw-attestations.schemas.js";

// PolicyRules Service
export { schemas as PolicyRulesSchemas } from "./policy-rules/schemas/policy-rules.schemas.js";

// RoyaltyShares Service
export { schemas as RoyaltySharesSchemas } from "./royalty-shares/schemas/royalty-shares.schemas.js";

