/**
 * Job Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/jobs.openapi.types.js";
import { schemas } from "../schemas/jobs.schemas.js";

/**
 * Entity: JobEntity
 * Description: Represents the Job domain model.
 * Source: schemas.Job
 * Type: Domain Entity (API)
 */
export const JobEntitySchema = schemas.Job;
export type JobEntity = components["schemas"]["Job"];
