/**
 * Job Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { JobEntity } from "@cogbazaar/core/jobs/models/index.js";
import { jobsSchemas } from "@cogbazaar/core/jobs";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "job";

export function createJob(overrides: Partial<JobEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    budgetAmount: overrides.budgetAmount ?? faker.number.int(),
    buyerParticipantId: overrides.buyerParticipantId ?? faker.string.uuid(),
    currency: overrides.currency ?? faker.lorem.word(),
    jobId: overrides.jobId ?? `job_${ulid().toLowerCase()}`,
    status: overrides.status ?? "draft",
    ...overrides,
  };

  return jobsSchemas.Job.parse(raw);
}

export function jobBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createJob(overrides));
}
