/**
 * Listing Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: listings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ListingEntity } from "@cogbazaar/core/listings/models/index.js";
import { listingsSchemas } from "@cogbazaar/core/listings";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "lst";

export function createListing(overrides: Partial<ListingEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    currency: overrides.currency ?? faker.lorem.word(),
    listingId: overrides.listingId ?? `lst_${ulid().toLowerCase()}`,
    listingType: overrides.listingType ?? "dataset",
    priceAmount: overrides.priceAmount ?? faker.number.int(),
    sellerParticipantId: overrides.sellerParticipantId ?? faker.string.uuid(),
    status: overrides.status ?? "active",
    ...overrides,
  };

  return listingsSchemas.Listing.parse(raw);
}

export function listingBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createListing(overrides));
}
