/**
 * Listings DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: listings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Listings Domain Module - Composition root
 *
 * DDD: Composition root for listings domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ListingRepositoryAdapter,
  SuspendRepositoryAdapter,
} from "@cogbazaar/adapters/listings";
import { getIdGeneratorService } from "@cogbazaar/adapters";
import type { AdapterDynamoDBClient } from "@cogbazaar/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateListing,
  ExecuteGetListing,
  ExecuteListListings,
  ExecuteSuspendListing,
  ExecuteUpdateListing,
} from "@cogbazaar/services/listings/usecases";
// Ports (interfaces)
import type {
  ListingRepository,
  SuspendRepository,
} from "@cogbazaar/services/listings/ports";

export interface ListingsDomainModule {
  repos: {
    listings: ListingRepository;
    suspends: SuspendRepository;
  };
  useCases: {
    listings: {
      create: ExecuteCreateListing;
      get: ExecuteGetListing;
      list: ExecuteListListings;
      update: ExecuteUpdateListing;
    };
    suspends: {
      get: ExecuteSuspendListing;
    };
  };
}

export function buildListingsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ListingsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      listings?: ListingRepository;
      suspends?: SuspendRepository;
    } = {};

    obj.listings = new ListingRepositoryAdapter(dynamoClient);
    obj.suspends = new SuspendRepositoryAdapter(dynamoClient);
    return {
      listings: obj.listings!,
      suspends: obj.suspends!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    listings: {
      create: new ExecuteCreateListing(executionContext, idGenerator, repos.listings),
      get: new ExecuteGetListing(executionContext, idGenerator, repos.listings),
      list: new ExecuteListListings(executionContext, idGenerator, repos.listings),
      update: new ExecuteUpdateListing(executionContext, idGenerator, repos.listings),
    },
    suspends: {
      get: new ExecuteSuspendListing(executionContext, idGenerator, repos.suspends),
    },
  };
  return { repos, useCases: useCases as ListingsDomainModule["useCases"] };
}
