/**
 * Listing DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: listings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Listing DTOs
 *
 * DDD: Application DTOs for Listing use cases.
 */

import type { CreateListingRequestInput, GetListingParams, ListListingsParams, UpdateListingParams, UpdateListingRequestInput } from "@cogbazaar/core/listings/types";

export type ListListingsInput = ListListingsParams;

export type CreateListingInput = CreateListingRequestInput;

export type GetListingInput = GetListingParams;

export type UpdateListingInput = UpdateListingParams & UpdateListingRequestInput;

export type ListListingsOutput = {};

export type CreateListingOutput = {};

export type GetListingOutput = {};

export type UpdateListingOutput = {};
