/**
 * Routes for PolicyRule
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policy-rules
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createPolicyRule, getPolicyRule, listPolicyRules } from "../handlers/policy-rule.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function policyRuleRoutes(fastify: FastifyInstance) {
  // POST /v1/policy-rules (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/policy-rules",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPolicyRulesDependenciesForRequest();
        await createPolicyRule(request, reply, deps);
      });
    }
  );


  // GET /v1/policy-rules (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/policy-rules",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPolicyRulesDependenciesForRequest();
        await listPolicyRules(request, reply, deps);
      });
    }
  );


  // GET /v1/policy-rules/{ruleId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/policy-rules/:ruleId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { ruleId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPolicyRulesDependenciesForRequest();
        await getPolicyRule(request, reply, deps);
      });
    }
  );


}
