/**
 * GetRoyaltyShare handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: royalty-shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getRoyaltyShare } from "@cogbazaar/api-server/domains/royalty-shares/handlers";
import type { RoyaltySharesDDDDependencies } from "@cogbazaar/api-server/domains/royalty-shares";
import { createRoyaltyShare as createRoyaltyShareEntity } from "@cogbazaar/factories/royalty-shares";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@cogbazaar/tests/shared";
import { ROYALTYSHARES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetRoyaltyShare", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: RoyaltySharesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<RoyaltySharesDDDDependencies>(
      ROYALTYSHARES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createRoyaltyShareEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetRoyaltyShare, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { shareId: entity.id };

    await getRoyaltyShare(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetRoyaltyShare.execute).toHaveBeenCalledWith(expect.objectContaining({ shareId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { shareId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetRoyaltyShare, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getRoyaltyShare(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
