/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: royalty-shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./create-royalty-share.handler.test.js";
export * from "./get-royalty-share.handler.test.js";
export * from "./list-royalty-shares.handler.test.js";
