/**
 * ListRoyaltyShares handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: royalty-shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listRoyaltyShares } from "@cogbazaar/api-server/domains/royalty-shares/handlers";
import type { RoyaltySharesDDDDependencies } from "@cogbazaar/api-server/domains/royalty-shares";
import { createRoyaltyShare as createRoyaltyShareEntity } from "@cogbazaar/factories/royalty-shares";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@cogbazaar/tests/shared";
import { ROYALTYSHARES_USE_CASES } from "../__factories__/use-cases.js";

describe("ListRoyaltyShares", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: RoyaltySharesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<RoyaltySharesDDDDependencies>(
      ROYALTYSHARES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createRoyaltyShareEntity({ orgId }),
      createRoyaltyShareEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListRoyaltyShares, "execute").mockResolvedValue(useCaseResult);

    await listRoyaltyShares(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListRoyaltyShares.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
