/**
 * Routes for RoyaltyShare
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: royalty-shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createRoyaltyShare, getRoyaltyShare, listRoyaltyShares } from "../handlers/royalty-share.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function royaltyShareRoutes(fastify: FastifyInstance) {
  // POST /v1/royalty-shares (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/royalty-shares",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getRoyaltySharesDependenciesForRequest();
        await createRoyaltyShare(request, reply, deps);
      });
    }
  );


  // GET /v1/royalty-shares (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/royalty-shares",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getRoyaltySharesDependenciesForRequest();
        await listRoyaltyShares(request, reply, deps);
      });
    }
  );


  // GET /v1/royalty-shares/{shareId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/royalty-shares/:shareId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { shareId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getRoyaltySharesDependenciesForRequest();
        await getRoyaltyShare(request, reply, deps);
      });
    }
  );


}
