/**
 * PolicyRuleRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policy-rules
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PolicyRuleRepository Port
 *
 * DDD: Application port for policyrulerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreatePolicyRuleInput, CreatePolicyRuleOutput, GetPolicyRuleInput, GetPolicyRuleOutput, ListPolicyRulesInput, ListPolicyRulesOutput } from "../dto/policy-rule.dto";
export interface PolicyRuleRepository {
  listPolicyRules(input: ListPolicyRulesInput): Promise<ListPolicyRulesOutput>;
  createPolicyRule(input: CreatePolicyRuleInput): Promise<CreatePolicyRuleOutput>;
  getPolicyRule(input: GetPolicyRuleInput): Promise<GetPolicyRuleOutput>;
}

export type { CreatePolicyRuleInput, CreatePolicyRuleOutput, GetPolicyRuleInput, GetPolicyRuleOutput, ListPolicyRulesInput, ListPolicyRulesOutput } from "../dto/policy-rule.dto";
