/**
 * ExecuteAcceptJobRoute - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteAcceptJobRoute Use Case
 *
 * DDD: Application use case for get AcceptRoute.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { AcceptJobRouteInput, AcceptJobRouteOutput } from "../dto/accept-route.dto";
import type { ExecutionContextService, IdGeneratorService } from "@cogbazaar/services/_shared/index.js";
import type { AcceptRouteRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteAcceptJobRoute {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly acceptRoute: AcceptRouteRepository
  ) {}

  async execute(input: AcceptJobRouteInput): Promise<AcceptJobRouteOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.jobId();

    // All field names extracted from OpenAPI spec: computeListingId, providerParticipantId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).jobId) {
      throw new ValidationError("jobId is required");
    }
    const jobId = (input as any).jobId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.acceptRoute.acceptJobRoute({ jobId: jobId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${jobId}`);
    }

    return entity as AcceptJobRouteOutput;
  }
}
