/**
 * ExecuteListJobs - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListJobs Use Case
 *
 * DDD: Application use case for list Job.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListJobsInput, ListJobsOutput } from "../dto/job.dto";
import type { ExecutionContextService, IdGeneratorService } from "@cogbazaar/services/_shared/index.js";
import type { JobRepository } from "../ports";

export class ExecuteListJobs {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly job: JobRepository
  ) {}

  async execute(input: ListJobsInput): Promise<ListJobsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.jobId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.job.listJobs({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListJobsOutput;
  }
}
