/**
 * ExecuteCancelJob - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCancelJob Use Case
 *
 * DDD: Application use case for update Cancel.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CancelJobInput, CancelJobOutput } from "../dto/cancel.dto";
import type { ExecutionContextService, IdGeneratorService } from "@cogbazaar/services/_shared/index.js";
import type { CancelRepository } from "../ports";
import { NotFoundError, PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteCancelJob {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly cancel: CancelRepository
  ) {}

  async execute(input: CancelJobInput): Promise<CancelJobOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.jobId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).jobId) {
      throw new ValidationError("jobId is required");
    }
    const jobId = (input as any).jobId;

    // Load existing entity
    const existing = await this.cancel.getJob({ jobId: jobId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!existing) {
      throw new NotFoundError(`Entity not found: ${jobId}`);
    }
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.cancel.cancelJob({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as CancelJobOutput;
  }
}
