/**
 * ExecuteCreateJob - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateJob Use Case
 *
 * DDD: Application use case for create Job.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateJobInput, CreateJobOutput } from "../dto/job.dto";
import type { ExecutionContextService, IdGeneratorService } from "@cogbazaar/services/_shared/index.js";
import type { JobRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateJob {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly job: JobRepository
  ) {}

  async execute(input: CreateJobInput): Promise<CreateJobOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.jobId();

    // All field names extracted from OpenAPI spec: agentBuyer, budgetAmount, buyerParticipantId, computeListingId, computeToData, containerSpec, currency, datasetListingId, kernelListingId, takeRateBps
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.buyerParticipantId) {
      throw new ValidationError("buyerParticipantId is required");
    }
    if (!input.budgetAmount) {
      throw new ValidationError("budgetAmount is required");
    }
    if (!input.currency) {
      throw new ValidationError("currency is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (jobs domain)
    const entityId = this.idGenerator.jobId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.job.createJob({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateJobOutput;
  }
}
