/**
 * Handlers for PocwAttestation
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pocw-attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { PocwAttestationsDomainModule } from "../dependencies/pocw-attestations-ddd.dependencies.js";
import type { GetPoCWAttestationInput, ListPoCWAttestationsInput, SubmitPoCWAttestationInput } from "@cogbazaar/services/pocw-attestations";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/pocw-attestations
 * Operation: listPoCWAttestations
 */
export async function listPoCWAttestations(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], jobId?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: PocwAttestationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListPoCWAttestationsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.pocwAttestations.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/pocw-attestations
 * Operation: submitPoCWAttestation
 */
export async function submitPoCWAttestation(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: PocwAttestationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: SubmitPoCWAttestationInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.pocwAttestations.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/pocw-attestations/{attestationId}
 * Operation: getPoCWAttestation
 */
export async function getPoCWAttestation(
  request: FastifyRequest<{ Params: { attestationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: PocwAttestationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetPoCWAttestationInput = {
    attestationId: request.params.attestationId,
  };
  const result = await deps.useCases.pocwAttestations.get.execute(input);
  return reply.code(200).send(result);
}


