/**
 * Handlers for Reject
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pocw-attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { PocwAttestationsDomainModule } from "../dependencies/pocw-attestations-ddd.dependencies.js";
import type { RejectPoCWAttestationInput } from "@cogbazaar/services/pocw-attestations";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/pocw-attestations/{attestationId}/reject
 * Operation: rejectPoCWAttestation
 */
export async function rejectPoCWAttestation(
  request: FastifyRequest<{ Params: { attestationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: PocwAttestationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RejectPoCWAttestationInput = {
    attestationId: request.params.attestationId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.rejects.create.execute(input);
  return reply.code(200).send(result);
}


