/**
 * ApproveDisbursement DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grant-pools
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ApproveDisbursement DTOs
 *
 * DDD: Application DTOs for ApproveDisbursement use cases.
 */

import type { ApproveGrantPoolDisbursementParams, ApproveGrantPoolDisbursementRequestInput } from "@cogbazaar/core/grant-pools/types";

export type ApproveGrantPoolDisbursementInput = ApproveGrantPoolDisbursementParams & ApproveGrantPoolDisbursementRequestInput;

export type ApproveGrantPoolDisbursementOutput = {};
