/**
 * DeclareMetric DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grant-pools
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DeclareMetric DTOs
 *
 * DDD: Application DTOs for DeclareMetric use cases.
 */

import type { DeclareGrantPoolMetricParams, DeclareGrantPoolMetricRequestInput } from "@cogbazaar/core/grant-pools/types";

export type DeclareGrantPoolMetricInput = DeclareGrantPoolMetricParams & DeclareGrantPoolMetricRequestInput;

export type DeclareGrantPoolMetricOutput = {};
