/**
 * GrantPool DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grant-pools
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * GrantPool DTOs
 *
 * DDD: Application DTOs for GrantPool use cases.
 */

import type { CreateGrantPoolRequestInput, GetGrantPoolParams, ListGrantPoolsParams } from "@cogbazaar/core/grant-pools/types";

export type ListGrantPoolsInput = ListGrantPoolsParams;

export type CreateGrantPoolInput = CreateGrantPoolRequestInput;

export type GetGrantPoolInput = GetGrantPoolParams;

export type ListGrantPoolsOutput = {};

export type CreateGrantPoolOutput = {};

export type GetGrantPoolOutput = {};
