/**
 * Handlers for Suspend
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: listings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ListingsDomainModule } from "../dependencies/listings-ddd.dependencies.js";
import type { SuspendListingInput } from "@cogbazaar/services/listings";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/listings/{listingId}/suspend
 * Operation: suspendListing
 */
export async function suspendListing(
  request: FastifyRequest<{ Params: { listingId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ListingsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: SuspendListingInput = {
    listingId: request.params.listingId,
  };
  const result = await deps.useCases.suspends.get.execute(input);
  return reply.code(200).send(result);
}


