/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: policy-rules
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@cogbazaar/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@cogbazaar/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@cogbazaar/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _grantPools from "./grant-pools/index.js";
import * as _identity from "./identity/index.js";
import * as _jobs from "./jobs/index.js";
import * as _listings from "./listings/index.js";
import * as _pocwAttestations from "./pocw-attestations/index.js";
import * as _policyRules from "./policy-rules/index.js";
import * as _royaltyShares from "./royalty-shares/index.js";

// Export as namespaces
export const grantPools = _grantPools;
export const identity = _identity;
export const jobs = _jobs;
export const listings = _listings;
export const pocwAttestations = _pocwAttestations;
export const policyRules = _policyRules;
export const royaltyShares = _royaltyShares;
