/**
 * GrantPool Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grant-pools
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/grant-pools.openapi.types.js";
import { schemas } from "../schemas/grant-pools.schemas.js";

/**
 * Entity: GrantPoolEntity
 * Description: Represents the GrantPool domain model.
 * Source: schemas.GrantPool
 * Type: Domain Entity (API)
 */
export const GrantPoolEntitySchema = schemas.GrantPool;
export type GrantPoolEntity = components["schemas"]["GrantPool"];
