/**
 * Repository interface for RoyaltyShare
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: royalty-shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  RoyaltyShareEntity
} from "../models/royalty-share.entity.js";
import type {
  ListRoyaltySharesParams,
  RoyaltyShare
} from "../types/index.js";
/**
 * RoyaltyShareRepository Interface
 */
export interface RoyaltyShareRepository extends CreateReadRepository<RoyaltyShareEntity, RoyaltyShare, string, ListRoyaltySharesParams> {

}
