/**
 * UpdateCancel DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { CancelJobParams } from "@cogbazaar/core/jobs";

export function createUpdateCancelRequest(overrides: Partial<CancelJobParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
