/**
 * ApproveDisbursementRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grant-pools
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ApproveDisbursementRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ApproveDisbursementRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ApproveDisbursementRepository,
} from "@cogbazaar/services/grant-pools";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ApproveDisbursementRepositoryDdb } from "./approve-disbursement-repository.ddb.js";

/**
 * ApproveDisbursementRepositoryAdapter
 *
 * Implements ApproveDisbursementRepository port for infrastructure layer.
 */
export class ApproveDisbursementRepositoryAdapter implements ApproveDisbursementRepository {
  private readonly ddb: ApproveDisbursementRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ApproveDisbursementRepositoryDdb(this.dynamoClient);
  }

  async approveGrantPoolDisbursement(input: Parameters<ApproveDisbursementRepository['approveGrantPoolDisbursement']>[0]): Promise<Awaited<ReturnType<ApproveDisbursementRepository['approveGrantPoolDisbursement']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.approveGrantPoolDisbursement(input);
  }
}
