/**
 * GrantPoolRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grant-pools
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * GrantPoolRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements GrantPoolRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  GrantPoolRepository,
} from "@cogbazaar/services/grant-pools";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { GrantPoolRepositoryDdb } from "./grant-pool-repository.ddb.js";

/**
 * GrantPoolRepositoryAdapter
 *
 * Implements GrantPoolRepository port for infrastructure layer.
 */
export class GrantPoolRepositoryAdapter implements GrantPoolRepository {
  private readonly ddb: GrantPoolRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new GrantPoolRepositoryDdb(this.dynamoClient);
  }

  async listGrantPools(input: Parameters<GrantPoolRepository['listGrantPools']>[0]): Promise<Awaited<ReturnType<GrantPoolRepository['listGrantPools']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listGrantPools(input);
  }

  async createGrantPool(input: Parameters<GrantPoolRepository['createGrantPool']>[0]): Promise<Awaited<ReturnType<GrantPoolRepository['createGrantPool']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createGrantPool(input);
  }

  async getGrantPool(input: Parameters<GrantPoolRepository['getGrantPool']>[0]): Promise<Awaited<ReturnType<GrantPoolRepository['getGrantPool']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getGrantPool(input);
  }
}
