/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grant-pools
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./approve-disbursement-repository.ddb.js";
export * from "./declare-metric-repository.ddb.js";
export * from "./grant-pool-repository.ddb.js";
export * from "./approve-disbursement-repository.adapter.js";
export * from "./declare-metric-repository.adapter.js";
export * from "./grant-pool-repository.adapter.js";
