/**
 * Handlers for Job
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { JobsDomainModule } from "../dependencies/jobs-ddd.dependencies.js";
import type { CreateJobInput, GetJobInput, ListJobsInput, UpdateJobInput } from "@cogbazaar/services/jobs";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/jobs
 * Operation: listJobs
 */
export async function listJobs(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[], buyerParticipantId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: JobsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListJobsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.jobs.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/jobs
 * Operation: createJob
 */
export async function createJob(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: JobsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateJobInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.jobs.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/jobs/{jobId}
 * Operation: getJob
 */
export async function getJob(
  request: FastifyRequest<{ Params: { jobId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: JobsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetJobInput = {
    jobId: request.params.jobId,
  };
  const result = await deps.useCases.jobs.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PATCH /v1/jobs/{jobId}
 * Operation: updateJob
 */
export async function updateJob(
  request: FastifyRequest<{ Params: { jobId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: JobsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpdateJobInput = {
    jobId: request.params.jobId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.jobs.update.execute(input);
  return reply.code(200).send(result);
}


