/**
 * Handlers for Refund
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { JobsDomainModule } from "../dependencies/jobs-ddd.dependencies.js";
import type { RefundJobInput } from "@cogbazaar/services/jobs";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/jobs/{jobId}/refund
 * Operation: refundJob
 */
export async function refundJob(
  request: FastifyRequest<{ Params: { jobId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: JobsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RefundJobInput = {
    jobId: request.params.jobId,
  };
  const result = await deps.useCases.refunds.get.execute(input);
  return reply.code(200).send(result);
}


