/**
 * PocwAttestation Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pocw-attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/pocw-attestations.openapi.types.js";
import { schemas } from "../schemas/pocw-attestations.schemas.js";

/**
 * Entity: PocwAttestationEntity
 * Description: Represents the PocwAttestation domain model.
 * Source: schemas.PoCWAttestation
 * Type: Domain Entity (API)
 */
export const PocwAttestationEntitySchema = schemas.PoCWAttestation;
export type PocwAttestationEntity = components["schemas"]["PoCWAttestation"];
