/**
 * ListingRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: listings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ListingRepository Port
 *
 * DDD: Application port for listingrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateListingInput, CreateListingOutput, GetListingInput, GetListingOutput, ListListingsInput, ListListingsOutput, UpdateListingInput, UpdateListingOutput } from "../dto/listing.dto";
export interface ListingRepository {
  listListings(input: ListListingsInput): Promise<ListListingsOutput>;
  createListing(input: CreateListingInput): Promise<CreateListingOutput>;
  getListing(input: GetListingInput): Promise<GetListingOutput>;
  updateListing(input: UpdateListingInput): Promise<UpdateListingOutput>;
}

export type { CreateListingInput, CreateListingOutput, GetListingInput, GetListingOutput, ListListingsInput, ListListingsOutput, UpdateListingInput, UpdateListingOutput } from "../dto/listing.dto";
