/**
 * GetJob handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getJob } from "@cogbazaar/api-server/domains/jobs/handlers";
import type { JobsDDDDependencies } from "@cogbazaar/api-server/domains/jobs";
import { createJob as createJobEntity } from "@cogbazaar/factories/jobs";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@cogbazaar/tests/shared";
import { JOBS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetJob", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: JobsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<JobsDDDDependencies>(
      JOBS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createJobEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetJob, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { jobId: entity.id };

    await getJob(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetJob.execute).toHaveBeenCalledWith(expect.objectContaining({ jobId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { jobId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetJob, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getJob(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
