/**
 * Handlers for PolicyRule
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policy-rules
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { PolicyRulesDomainModule } from "../dependencies/policy-rules-ddd.dependencies.js";
import type { CreatePolicyRuleInput, GetPolicyRuleInput, ListPolicyRulesInput } from "@cogbazaar/services/policy-rules";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/policy-rules
 * Operation: listPolicyRules
 */
export async function listPolicyRules(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], ruleType?: string | string[], status?: string | string[], dualUseQueue?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: PolicyRulesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListPolicyRulesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.policyRules.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/policy-rules
 * Operation: createPolicyRule
 */
export async function createPolicyRule(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: PolicyRulesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreatePolicyRuleInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.policyRules.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/policy-rules/{ruleId}
 * Operation: getPolicyRule
 */
export async function getPolicyRule(
  request: FastifyRequest<{ Params: { ruleId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: PolicyRulesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetPolicyRuleInput = {
    ruleId: request.params.ruleId,
  };
  const result = await deps.useCases.policyRules.get.execute(input);
  return reply.code(200).send(result);
}


