/**
 * RoyaltyShareRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: royalty-shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RoyaltyShareRepository Port
 *
 * DDD: Application port for royaltysharerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateRoyaltyShareInput, CreateRoyaltyShareOutput, GetRoyaltyShareInput, GetRoyaltyShareOutput, ListRoyaltySharesInput, ListRoyaltySharesOutput } from "../dto/royalty-share.dto";
export interface RoyaltyShareRepository {
  listRoyaltyShares(input: ListRoyaltySharesInput): Promise<ListRoyaltySharesOutput>;
  createRoyaltyShare(input: CreateRoyaltyShareInput): Promise<CreateRoyaltyShareOutput>;
  getRoyaltyShare(input: GetRoyaltyShareInput): Promise<GetRoyaltyShareOutput>;
}

export type { CreateRoyaltyShareInput, CreateRoyaltyShareOutput, GetRoyaltyShareInput, GetRoyaltyShareOutput, ListRoyaltySharesInput, ListRoyaltySharesOutput } from "../dto/royalty-share.dto";
