/**
 * ListPocwAttestation DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pocw-attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListPoCWAttestationsParams } from "@cogbazaar/core/pocw-attestations";

export function createListPocwAttestationRequest(overrides: Partial<ListPoCWAttestationsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
