/**
 * Handlers for ApproveDisbursement
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grant-pools
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { GrantPoolsDomainModule } from "../dependencies/grant-pools-ddd.dependencies.js";
import type { ApproveGrantPoolDisbursementInput } from "@cogbazaar/services/grant-pools";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/grant-pools/{poolId}/approve-disbursement
 * Operation: approveGrantPoolDisbursement
 */
export async function approveGrantPoolDisbursement(
  request: FastifyRequest<{ Params: { poolId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: GrantPoolsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ApproveGrantPoolDisbursementInput = {
    poolId: request.params.poolId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.approveDisbursements.create.execute(input);
  return reply.code(200).send(result);
}


