/**
 * Handlers for GrantPool
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grant-pools
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { GrantPoolsDomainModule } from "../dependencies/grant-pools-ddd.dependencies.js";
import type { CreateGrantPoolInput, GetGrantPoolInput, ListGrantPoolsInput } from "@cogbazaar/services/grant-pools";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/grant-pools
 * Operation: listGrantPools
 */
export async function listGrantPools(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: GrantPoolsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListGrantPoolsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.grantPools.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/grant-pools
 * Operation: createGrantPool
 */
export async function createGrantPool(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: GrantPoolsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateGrantPoolInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.grantPools.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/grant-pools/{poolId}
 * Operation: getGrantPool
 */
export async function getGrantPool(
  request: FastifyRequest<{ Params: { poolId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: GrantPoolsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetGrantPoolInput = {
    poolId: request.params.poolId,
  };
  const result = await deps.useCases.grantPools.get.execute(input);
  return reply.code(200).send(result);
}


