/**
 * GrantPools DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grant-pools
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * GrantPools Domain Module - Composition root
 *
 * DDD: Composition root for grant-pools domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ApproveDisbursementRepositoryAdapter,
  DeclareMetricRepositoryAdapter,
  GrantPoolRepositoryAdapter,
} from "@cogbazaar/adapters/grant-pools";
import { getIdGeneratorService } from "@cogbazaar/adapters";
import type { AdapterDynamoDBClient } from "@cogbazaar/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteApproveGrantPoolDisbursement,
  ExecuteCreateGrantPool,
  ExecuteDeclareGrantPoolMetric,
  ExecuteGetGrantPool,
  ExecuteListGrantPools,
} from "@cogbazaar/services/grant-pools/usecases";
// Ports (interfaces)
import type {
  ApproveDisbursementRepository,
  DeclareMetricRepository,
  GrantPoolRepository,
} from "@cogbazaar/services/grant-pools/ports";

export interface GrantPoolsDomainModule {
  repos: {
    approveDisbursements: ApproveDisbursementRepository;
    declareMetrics: DeclareMetricRepository;
    grantPools: GrantPoolRepository;
  };
  useCases: {
    approveDisbursements: {
      create: ExecuteApproveGrantPoolDisbursement;
    };
    declareMetrics: {
      get: ExecuteDeclareGrantPoolMetric;
    };
    grantPools: {
      create: ExecuteCreateGrantPool;
      get: ExecuteGetGrantPool;
      list: ExecuteListGrantPools;
    };
  };
}

export function buildGrantPoolsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): GrantPoolsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      approveDisbursements?: ApproveDisbursementRepository;
      declareMetrics?: DeclareMetricRepository;
      grantPools?: GrantPoolRepository;
    } = {};

    obj.approveDisbursements = new ApproveDisbursementRepositoryAdapter(dynamoClient);
    obj.declareMetrics = new DeclareMetricRepositoryAdapter(dynamoClient);
    obj.grantPools = new GrantPoolRepositoryAdapter(dynamoClient);
    return {
      approveDisbursements: obj.approveDisbursements!,
      declareMetrics: obj.declareMetrics!,
      grantPools: obj.grantPools!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    approveDisbursements: {
      create: new ExecuteApproveGrantPoolDisbursement(executionContext, idGenerator, repos.approveDisbursements),
    },
    declareMetrics: {
      get: new ExecuteDeclareGrantPoolMetric(executionContext, idGenerator, repos.declareMetrics),
    },
    grantPools: {
      create: new ExecuteCreateGrantPool(executionContext, idGenerator, repos.grantPools),
      get: new ExecuteGetGrantPool(executionContext, idGenerator, repos.grantPools),
      list: new ExecuteListGrantPools(executionContext, idGenerator, repos.grantPools),
    },
  };
  return { repos, useCases: useCases as GrantPoolsDomainModule["useCases"] };
}
