/**
 * Repository interface for PolicyRule
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: policy-rules
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  PolicyRuleEntity
} from "../models/policy-rule.entity.js";
import type {
  ListPolicyRulesParams,
  PolicyRule
} from "../types/index.js";
/**
 * PolicyRuleRepository Interface
 */
export interface PolicyRuleRepository extends CreateReadRepository<PolicyRuleEntity, PolicyRule, string, ListPolicyRulesParams> {

}
