/**
 * Routes for PocwAttestation
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pocw-attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getPoCWAttestation, listPoCWAttestations, submitPoCWAttestation } from "../handlers/pocw-attestation.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function pocwAttestationRoutes(fastify: FastifyInstance) {
  // GET /v1/pocw-attestations (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/pocw-attestations",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPocwAttestationsDependenciesForRequest();
        await listPoCWAttestations(request, reply, deps);
      });
    }
  );


  // POST /v1/pocw-attestations (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/pocw-attestations",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPocwAttestationsDependenciesForRequest();
        await submitPoCWAttestation(request, reply, deps);
      });
    }
  );


  // GET /v1/pocw-attestations/{attestationId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/pocw-attestations/:attestationId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { attestationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPocwAttestationsDependenciesForRequest();
        await getPoCWAttestation(request, reply, deps);
      });
    }
  );


}
