/**
 * CreatePolicyRule handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policy-rules
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createPolicyRule } from "@cogbazaar/api-server/domains/policy-rules/handlers";
import type { PolicyRulesDDDDependencies } from "@cogbazaar/api-server/domains/policy-rules";
import { createPolicyRule as createPolicyRuleEntity } from "@cogbazaar/factories/policy-rules";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@cogbazaar/tests/shared";
import { POLICYRULES_USE_CASES } from "../__factories__/use-cases.js";

describe("CreatePolicyRule", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: PolicyRulesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<PolicyRulesDDDDependencies>(
      POLICYRULES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createPolicyRuleEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreatePolicyRule, "execute").mockResolvedValue(useCaseResult);

    await createPolicyRule(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreatePolicyRule.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
