/**
 * GetPolicyRule handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policy-rules
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getPolicyRule } from "@cogbazaar/api-server/domains/policy-rules/handlers";
import type { PolicyRulesDDDDependencies } from "@cogbazaar/api-server/domains/policy-rules";
import { createPolicyRule as createPolicyRuleEntity } from "@cogbazaar/factories/policy-rules";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@cogbazaar/tests/shared";
import { POLICYRULES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetPolicyRule", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: PolicyRulesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<PolicyRulesDDDDependencies>(
      POLICYRULES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createPolicyRuleEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetPolicyRule, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { ruleId: entity.id };

    await getPolicyRule(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetPolicyRule.execute).toHaveBeenCalledWith(expect.objectContaining({ ruleId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { ruleId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetPolicyRule, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getPolicyRule(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
