/**
 * ListPolicyRules handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policy-rules
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listPolicyRules } from "@cogbazaar/api-server/domains/policy-rules/handlers";
import type { PolicyRulesDDDDependencies } from "@cogbazaar/api-server/domains/policy-rules";
import { createPolicyRule as createPolicyRuleEntity } from "@cogbazaar/factories/policy-rules";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@cogbazaar/tests/shared";
import { POLICYRULES_USE_CASES } from "../__factories__/use-cases.js";

describe("ListPolicyRules", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: PolicyRulesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<PolicyRulesDDDDependencies>(
      POLICYRULES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createPolicyRuleEntity({ orgId }),
      createPolicyRuleEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListPolicyRules, "execute").mockResolvedValue(useCaseResult);

    await listPolicyRules(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListPolicyRules.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
