/**
 * Listing Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: listings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/listings.openapi.types.js";
import { schemas } from "../schemas/listings.schemas.js";

/**
 * Entity: ListingEntity
 * Description: Represents the Listing domain model.
 * Source: schemas.Listing
 * Type: Domain Entity (API)
 */
export const ListingEntitySchema = schemas.Listing;
export type ListingEntity = components["schemas"]["Listing"];
