/**
 * Repository interface for Listing
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: listings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateUpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ListingEntity
} from "../models/listing.entity.js";
import type {
  ListListingsParams,
  Listing,
  UpdateListingRequestInput
} from "../types/index.js";
/**
 * ListingRepository Interface
 */
export interface ListingRepository extends CreateUpdateReadRepository<ListingEntity, Listing, UpdateListingRequestInput, string, ListListingsParams> {

}
