/**
 * PocwAttestations Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pocw-attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const submitPoCWAttestation_Body = z
  .object({
    jobId: z.string(),
    providerParticipantId: z.string(),
    proofPayload: z.string(),
    proofFormat: z.string().optional(),
  })
  .passthrough();

export const schemas: any = {
  submitPoCWAttestation_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/pocw-attestations',
    alias: 'listPoCWAttestations',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(100).optional().default(25),
      },
      {
        name: 'jobId',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'status',
        type: 'Query',
        schema: z
          .enum(['pending', 'accepted', 'rejected', 'exportReady'])
          .optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  attestationId: z
                    .string()
                    .regex(/^pcw_[0-9A-HJKMNP-TV-Z]{26}$/),
                  jobId: z.string(),
                  providerParticipantId: z.string(),
                  status: z.enum([
                    'pending',
                    'accepted',
                    'rejected',
                    'exportReady',
                  ]),
                  accepted: z.boolean().optional(),
                  proofPayload: z.string().optional(),
                  proofFormat: z.string().optional(),
                  rejectReason: z.string().optional(),
                  exportPackUrl: z.string().optional(),
                  submittedAt: z.string().datetime({ offset: true }),
                  reviewedAt: z.string().datetime({ offset: true }).optional(),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/pocw-attestations',
    alias: 'submitPoCWAttestation',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: submitPoCWAttestation_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            attestationId: z.string().regex(/^pcw_[0-9A-HJKMNP-TV-Z]{26}$/),
            jobId: z.string(),
            providerParticipantId: z.string(),
            status: z.enum(['pending', 'accepted', 'rejected', 'exportReady']),
            accepted: z.boolean().optional(),
            proofPayload: z.string().optional(),
            proofFormat: z.string().optional(),
            rejectReason: z.string().optional(),
            exportPackUrl: z.string().optional(),
            submittedAt: z.string().datetime({ offset: true }),
            reviewedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/pocw-attestations/:attestationId',
    alias: 'getPoCWAttestation',
    requestFormat: 'json',
    parameters: [
      {
        name: 'attestationId',
        type: 'Path',
        schema: z.string().regex(/^pcw_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            attestationId: z.string().regex(/^pcw_[0-9A-HJKMNP-TV-Z]{26}$/),
            jobId: z.string(),
            providerParticipantId: z.string(),
            status: z.enum(['pending', 'accepted', 'rejected', 'exportReady']),
            accepted: z.boolean().optional(),
            proofPayload: z.string().optional(),
            proofFormat: z.string().optional(),
            rejectReason: z.string().optional(),
            exportPackUrl: z.string().optional(),
            submittedAt: z.string().datetime({ offset: true }),
            reviewedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/pocw-attestations/:attestationId/accept',
    alias: 'acceptPoCWAttestation',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: z
          .object({ reason: z.string() })
          .partial()
          .passthrough()
          .optional(),
      },
      {
        name: 'attestationId',
        type: 'Path',
        schema: z.string().regex(/^pcw_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            attestationId: z.string().regex(/^pcw_[0-9A-HJKMNP-TV-Z]{26}$/),
            jobId: z.string(),
            providerParticipantId: z.string(),
            status: z.enum(['pending', 'accepted', 'rejected', 'exportReady']),
            accepted: z.boolean().optional(),
            proofPayload: z.string().optional(),
            proofFormat: z.string().optional(),
            rejectReason: z.string().optional(),
            exportPackUrl: z.string().optional(),
            submittedAt: z.string().datetime({ offset: true }),
            reviewedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 409,
        description: `Idempotency key reuse with different body, or state conflict`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/pocw-attestations/:attestationId/export-pack',
    alias: 'exportPoCWAttestationPack',
    requestFormat: 'json',
    parameters: [
      {
        name: 'attestationId',
        type: 'Path',
        schema: z.string().regex(/^pcw_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            attestationId: z.string().regex(/^pcw_[0-9A-HJKMNP-TV-Z]{26}$/),
            packDigest: z.string(),
            exportPackUrl: z.string().optional(),
            exportedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/pocw-attestations/:attestationId/reject',
    alias: 'rejectPoCWAttestation',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: z.object({ reason: z.string() }).partial().passthrough(),
      },
      {
        name: 'attestationId',
        type: 'Path',
        schema: z.string().regex(/^pcw_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            attestationId: z.string().regex(/^pcw_[0-9A-HJKMNP-TV-Z]{26}$/),
            jobId: z.string(),
            providerParticipantId: z.string(),
            status: z.enum(['pending', 'accepted', 'rejected', 'exportReady']),
            accepted: z.boolean().optional(),
            proofPayload: z.string().optional(),
            proofFormat: z.string().optional(),
            rejectReason: z.string().optional(),
            exportPackUrl: z.string().optional(),
            submittedAt: z.string().datetime({ offset: true }),
            reviewedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
