/**
 * RoyaltyShare Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: royalty-shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { RoyaltyShareEntity } from "@cogbazaar/core/royalty-shares/models/index.js";
import { royaltySharesSchemas } from "@cogbazaar/core/royalty-shares";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "ryl";

export function createRoyaltyShare(overrides: Partial<RoyaltyShareEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    amount: overrides.amount ?? faker.number.int(),
    currency: overrides.currency ?? faker.lorem.word(),
    jobId: overrides.jobId ?? faker.string.uuid(),
    payeeParticipantId: overrides.payeeParticipantId ?? faker.string.uuid(),
    role: overrides.role ?? "data",
    shareBps: overrides.shareBps ?? faker.number.int(),
    shareId: overrides.shareId ?? `ryl_${ulid().toLowerCase()}`,
    status: overrides.status ?? "pending",
    ...overrides,
  };

  return royaltySharesSchemas.RoyaltyShare.parse(raw);
}

export function royaltyShareBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createRoyaltyShare(overrides));
}
