/**
 * ExecuteGetRoyaltyShare - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: royalty-shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetRoyaltyShare Use Case
 *
 * DDD: Application use case for get RoyaltyShare.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetRoyaltyShareInput, GetRoyaltyShareOutput } from "../dto/royalty-share.dto";
import type { ExecutionContextService, IdGeneratorService } from "@cogbazaar/services/_shared/index.js";
import type { RoyaltyShareRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetRoyaltyShare {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly royaltyShare: RoyaltyShareRepository
  ) {}

  async execute(input: GetRoyaltyShareInput): Promise<GetRoyaltyShareOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rylId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).shareId) {
      throw new ValidationError("shareId is required");
    }
    const shareId = (input as any).shareId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.royaltyShare.getRoyaltyShare({ shareId: shareId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${shareId}`);
    }

    return entity as GetRoyaltyShareOutput;
  }
}
