/**
 * ExecuteCreateRoyaltyShare - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: royalty-shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateRoyaltyShare Use Case
 *
 * DDD: Application use case for create RoyaltyShare.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateRoyaltyShareInput, CreateRoyaltyShareOutput } from "../dto/royalty-share.dto";
import type { ExecutionContextService, IdGeneratorService } from "@cogbazaar/services/_shared/index.js";
import type { RoyaltyShareRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateRoyaltyShare {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly royaltyShare: RoyaltyShareRepository
  ) {}

  async execute(input: CreateRoyaltyShareInput): Promise<CreateRoyaltyShareOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rylId();

    // All field names extracted from OpenAPI spec: amount, currency, jobId, payeeParticipantId, periodKey, role, shareBps, status
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.currency) {
      throw new ValidationError("currency is required");
    }
    if (!input.role) {
      throw new ValidationError("role is required");
    }
    if (!input.payeeParticipantId) {
      throw new ValidationError("payeeParticipantId is required");
    }
    if (!input.shareBps) {
      throw new ValidationError("shareBps is required");
    }
    if (!input.jobId) {
      throw new ValidationError("jobId is required");
    }
    if (!input.amount) {
      throw new ValidationError("amount is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (royalty-shares domain)
    const entityId = this.idGenerator.rylId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.royaltyShare.createRoyaltyShare({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateRoyaltyShareOutput;
  }
}
