/**
 * ExecuteListRoyaltyShares - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: royalty-shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListRoyaltyShares Use Case
 *
 * DDD: Application use case for list RoyaltyShare.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListRoyaltySharesInput, ListRoyaltySharesOutput } from "../dto/royalty-share.dto";
import type { ExecutionContextService, IdGeneratorService } from "@cogbazaar/services/_shared/index.js";
import type { RoyaltyShareRepository } from "../ports";

export class ExecuteListRoyaltyShares {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly royaltyShare: RoyaltyShareRepository
  ) {}

  async execute(input: ListRoyaltySharesInput): Promise<ListRoyaltySharesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rylId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.royaltyShare.listRoyaltyShares({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListRoyaltySharesOutput;
  }
}
