/**
 * ExportPoCWAttestationPack handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pocw-attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { exportPoCWAttestationPack } from "@cogbazaar/api-server/domains/pocw-attestations/handlers";
import type { PocwAttestationsDDDDependencies } from "@cogbazaar/api-server/domains/pocw-attestations";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@cogbazaar/tests/shared";
import { POCWATTESTATIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("ExportPoCWAttestationPack", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: PocwAttestationsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<PocwAttestationsDDDDependencies>(
      POCWATTESTATIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      { id: 'mock-1', orgId } as any,
      { id: 'mock-2', orgId } as any,
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeExportPoCWAttestationPack, "execute").mockResolvedValue(useCaseResult);

    await exportPoCWAttestationPack(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeExportPoCWAttestationPack.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
